- name: Build job file from templates
  ansible.builtin.template:
    src: mbranch.xml
    dest: /tmp/mbranch.xml

- name: Create a Multi branch pipeline
  community.general.jenkins_job:
    config: "{{ lookup('file', '/tmp/mbranch.xml') }}"
    name: "ci-pipelines/{{item.name}}"
    password: admin123
    url: http://172.31.46.80:8080
    user: admin
